#!/usr/bin/env sh

if [ "$#" -gt 0 ]; then
  NX_LITE_HAS_ARGS=1
  NX_LITE_INPUT=$*
else
  NX_LITE_HAS_ARGS=0
  NX_LITE_INPUT=
fi
export NX_LITE_HAS_ARGS NX_LITE_INPUT

LC_ALL=C awk '
function init_ord(    i) {
  for (i = 1; i < 256; i++) {
    ordv[sprintf("%c", i)] = i
  }
}

function init_md5(    ktmp, stmp, i) {
  MOD = 4294967296
  MASK = 4294967295
  HEX = "0123456789abcdef"

  pow2[0] = 1
  for (i = 1; i <= 32; i++) {
    pow2[i] = pow2[i - 1] * 2
  }

  split("3614090360 3905402710 606105819 3250441966 4118548399 1200080426 2821735955 4249261313 1770035416 2336552879 4294925233 2304563134 1804603682 4254626195 2792965006 1236535329 4129170786 3225465664 643717713 3921069994 3593408605 38016083 3634488961 3889429448 568446438 3275163606 4107603335 1163531501 2850285829 4243563512 1735328473 2368359562 4294588738 2272392833 1839030562 4259657740 2763975236 1272893353 4139469664 3200236656 681279174 3936430074 3572445317 76029189 3654602809 3873151461 530742520 3299628645 4096336452 1126891415 2878612391 4237533241 1700485571 2399980690 4293915773 2240044497 1873313359 4264355552 2734768916 1309151649 4149444226 3174756917 718787259 3951481745", ktmp, " ")
  split("7 12 17 22 7 12 17 22 7 12 17 22 7 12 17 22 5 9 14 20 5 9 14 20 5 9 14 20 5 9 14 20 4 11 16 23 4 11 16 23 4 11 16 23 4 11 16 23 6 10 15 21 6 10 15 21 6 10 15 21 6 10 15 21", stmp, " ")

  for (i = 0; i < 64; i++) {
    K[i] = ktmp[i + 1] + 0
    S[i] = stmp[i + 1] + 0
  }
}

function add32(a, b,    r) {
  r = (a + b) % MOD
  return r < 0 ? r + MOD : r
}

function bit_and(a, b,    r, p, aa, bb) {
  r = 0
  p = 1
  while (a > 0 || b > 0) {
    aa = a % 2
    bb = b % 2
    if (aa && bb) {
      r += p
    }
    a = int(a / 2)
    b = int(b / 2)
    p *= 2
  }
  return r
}

function bit_or(a, b,    r, p, aa, bb) {
  r = 0
  p = 1
  while (a > 0 || b > 0) {
    aa = a % 2
    bb = b % 2
    if (aa || bb) {
      r += p
    }
    a = int(a / 2)
    b = int(b / 2)
    p *= 2
  }
  return r
}

function bit_xor(a, b,    r, p, aa, bb) {
  r = 0
  p = 1
  while (a > 0 || b > 0) {
    aa = a % 2
    bb = b % 2
    if ((aa && !bb) || (!aa && bb)) {
      r += p
    }
    a = int(a / 2)
    b = int(b / 2)
    p *= 2
  }
  return r
}

function bit_not(a) {
  return MASK - a
}

function lshift32(a, n,    i) {
  for (i = 0; i < n; i++) {
    a = (a * 2) % MOD
  }
  return a
}

function rshift32(a, n) {
  return int(a / pow2[n])
}

function leftrotate(a, n) {
  return add32(lshift32(a, n), rshift32(a, 32 - n))
}

function byte_hex(b) {
  b = int(b) % 256
  return substr(HEX, int(b / 16) + 1, 1) substr(HEX, (b % 16) + 1, 1)
}

function word_hex_le(w) {
  return byte_hex(w % 256) byte_hex(int(w / 256) % 256) byte_hex(int(w / 65536) % 256) byte_hex(int(w / 16777216) % 256)
}

function digest(msg,    len, i, total, bitlen, low, high, offset, j, k, h0, h1, h2, h3, a, b, c, d, f, g, temp, x, bytes, m) {
  len = length(msg)
  for (i = 1; i <= len; i++) {
    bytes[i - 1] = ordv[substr(msg, i, 1)]
  }

  bytes[len] = 128
  total = len + 1
  while (total % 64 != 56) {
    bytes[total] = 0
    total++
  }

  bitlen = len * 8
  low = bitlen % MOD
  high = int(bitlen / MOD)
  for (i = 0; i < 4; i++) {
    bytes[total + i] = int(low / pow2[8 * i]) % 256
    bytes[total + 4 + i] = int(high / pow2[8 * i]) % 256
  }
  total += 8

  h0 = 1732584193
  h1 = 4023233417
  h2 = 2562383102
  h3 = 271733878

  for (offset = 0; offset < total; offset += 64) {
    for (j = 0; j < 16; j++) {
      k = offset + j * 4
      m[j] = bytes[k] + bytes[k + 1] * 256 + bytes[k + 2] * 65536 + bytes[k + 3] * 16777216
    }

    a = h0
    b = h1
    c = h2
    d = h3

    for (i = 0; i < 64; i++) {
      if (i < 16) {
        f = bit_or(bit_and(b, c), bit_and(bit_not(b), d))
        g = i
      } else if (i < 32) {
        f = bit_or(bit_and(d, b), bit_and(bit_not(d), c))
        g = (5 * i + 1) % 16
      } else if (i < 48) {
        f = bit_xor(bit_xor(b, c), d)
        g = (3 * i + 5) % 16
      } else {
        f = bit_xor(c, bit_or(b, bit_not(d)))
        g = (7 * i) % 16
      }

      temp = d
      d = c
      c = b
      x = add32(add32(a, f), add32(K[i], m[g]))
      b = add32(b, leftrotate(x, S[i]))
      a = temp
    }

    h0 = add32(h0, a)
    h1 = add32(h1, b)
    h2 = add32(h2, c)
    h3 = add32(h3, d)
  }

  return word_hex_le(h0) word_hex_le(h1) word_hex_le(h2) word_hex_le(h3)
}

BEGIN {
  init_ord()
  init_md5()
  from_args = (ENVIRON["NX_LITE_HAS_ARGS"] == "1")
  if (from_args) {
    text = ENVIRON["NX_LITE_INPUT"]
    exit
  }
}

!from_args {
  text = text (seen ? "\n" : "") $0
  seen = 1
}

END {
  print digest(text)
}
'
